services:
  - type: web
    name: uav-security-ml
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --noinput"
    startCommand: "bash startup.sh"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: uav_project.settings
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: ".onrender.com localhost 127.0.0.1"
      - key: SECRET_KEY
        generateValue: true
      - key: ADMIN_USERNAME
        value: admin
      - key: ADMIN_PASSWORD
        generateValue: true
      - key: ADMIN_EMAIL
        value: admin@uavsecurity.com
      - key: PYTHON_VERSION
        value: "3.11"
      - key: SECURE_SSL_REDIRECT
        value: "False"
    disk:
      name: uav-data
      mountPath: /opt/render/project/src/ml_models
      sizeGB: 1